### ISSUE TITLE
source code

### ISSUE THREAD

**Issue by 761324428** [grepthat/odrviewer#1]
I am a cardholder from China. Can you open source the core code? I really need him now, and I will label the original author. Thank you very much

**Comment by pageldev** [comment]
I'm not planning on releasing the source code. What do you need it for?

**Comment by 761324428** [comment]
I just want to visualize XODR in the intranet. Currently, I only have 2D visualization, and I need 3D now. 3D looks even more cool

**Comment by 761324428** [comment]
If it's really not open source, then I'll use the online version

**Comment by 761324428** [comment]
或者您有类似的开源项目，可以推介给我

**Comment by 761324428** [comment]
Or if you have a similar open source project, you can recommend it to me

**Comment by pageldev** [comment]
You can host it offline or in the intranet by simply downloading the files and serving them. Like this:

```bash
wget https://odrviewer.io/viewer.js https://odrviewer.io/viewer.wasm https://odrviewer.io/viewer.data https://odrviewer.io/index.html https://odrviewer.io/fonts/bootstrap.min.css https://odrviewer.io/fonts/font-awesome.min.css https://odrviewer.io/fonts/fontawesome-webfont.woff2 
mkdir fonts
mv bootstrap.min.css font-awesome.min.css fontawesome-webfont.woff2 fonts/
python3 -m http.server
```

**Comment by 761324428** [comment]
I'll give it a try. Thank you very much
