### ISSUE TITLE
viewer 这部分code可以开源吗

### ISSUE THREAD

**Issue by army82** [grepthat/odrviewer#8]
你好，我看到文章中有viewer.wasm,这部分可以开源学习下吗

**Comment by pageldev** [comment]
please use English for discussions here

**Comment by pageldev** [comment]
> The core of the viewer is closed-source with only the public assets being hosted here.

**Comment by army82** [comment]
Thank you!





------------------ 原始邮件 ------------------
发件人: Sebastian Pagel ***@***.***&gt;
发送时间: 2024年11月13日 01:06
收件人: pageldev/odrviewer ***@***.***&gt;
抄送: army82 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [pageldev/odrviewer] viewer 这部分code可以开源吗 (Issue #8)





  
The core of the viewer is closed-source with only the public assets being hosted here.
